### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by hackable** [bjarnel/arkit-graffiti#1]
Hi Sorry the app opens but cannot draw anything after clicking on new wall

**Comment by dumbfingers** [comment]
same here.

Tried under 11.2 beta2 with different light conditions.

Are we doing something wrong?

**Comment by FirstRound** [comment]
Same

**Comment by bjarnel** [comment]
I have added tracking state information on screen. It should make it easier to understand what is going on.
